# Generated by Django 5.0 on 2025-12-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0014_vivasessionsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignment_resources/')),
                ('comment', models.TextField(blank=True)),
                ('included', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tool.assignment')),
            ],
        ),
    ]
