# Generated by Django 5.0 on 2025-12-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0015_assignmentresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivamessage',
            name='model_answer',
            field=models.TextField(blank=True),
        ),
    ]
