# Generated by Django 5.0 on 2025-12-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0016_vivamessage_model_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='enable_model_answers',
            field=models.BooleanField(default=True),
        ),
    ]
