# Generated by Django 5.0 on 2025-12-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0017_assignment_enable_model_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
