# Generated by Django 5.0 on 2025-12-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0018_submission_is_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_student_resource_toggle',
            field=models.BooleanField(default=False),
        ),
    ]
