# Generated by Django 5.0 on 2025-12-19 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0019_assignment_allow_student_resource_toggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VivaSessionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_links', to='tool.assignmentresource')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='tool.vivasession')),
            ],
            options={
                'unique_together': {('session', 'resource')},
            },
        ),
    ]
