# Generated by Django 5.0 on 2025-12-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0023_userprofile_verification_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assignmentinvitation',
            new_name='tool_assign_token_529526_idx',
            old_name='tool_assign_token_0ca1b2_idx',
        ),
        migrations.RenameIndex(
            model_name='assignmentinvitation',
            new_name='tool_assign_email_ca4ce6_idx',
            old_name='tool_assign_email_b02655_idx',
        ),
    ]
