# Generated by Django 5.0 on 2025-12-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0029_merge_invite_role_self_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='allow_early_submission',
            field=models.BooleanField(default=False, help_text='Allow students to submit the viva before time expires.'),
        ),
    ]
