# Generated by Django 5.0 on 2026-01-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0041_alter_article_id'),
        ('tool', '0041_assignmentsettingschange'),
    ]

    operations = [
    ]
