# Generated by Django 5.0 on 2026-01-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0042_merge_20260109_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsettingschange',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
