# Generated by Django 5.0 on 2026-01-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0043_alter_assignmentsettingschange_id'),
        ('tool', '0043_assignment_allow_student_uploads'),
    ]

    operations = [
    ]
